# Generated by Django 5.1.3 on 2024-12-06 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_auctionlisting_id_alter_bid_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watched_by", to="auctions.auctionlisting"
            ),
        ),
    ]
