# Generated by Django 5.1.3 on 2025-02-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_category_auctionlisting_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
