# Generated by Django 5.1.3 on 2025-02-06 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_auctionlisting_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
