# Generated by Django 5.1.3 on 2025-02-18 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_alter_auctionlisting_watchlist_alter_user_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="watchlist",
        ),
    ]
