# Generated by Django 5.1.6 on 2025-06-03 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
