# Generated by Django 5.1.6 on 2025-06-03 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
