# Generated by Django 5.1.6 on 2025-06-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servico", models.CharField(max_length=200)),
                ("observacoes", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
